### PR TITLE
Draft of CI actions.

### PR DESCRIPTION
**Pull request by kierans**
The CI flow will build, test, publish, and tag changes to the SDK.

I've run some tests (if you look at the Actions logs) and it all works. I've based on CI config I've used for other Node projects.

### CODE REVIEW

**Comment by kierans** [comment]
Fixes #3 and #4

**Review by bfarrelly — COMMENTED** [review]
Looks good.  

Not going to do anything about auto bumping minor versions?  Woolies pipelines all handle the versioning for the services.

**Comment by kierans** [comment]
> Not going to do anything about auto bumping minor versions?

I don't auto bumping of version numbers. It should be the devs who decide what type of change it should be ie: major, minor, patch.

While some tools provide help in deciding the the new version I'd prefer a more intelligent approach to version management.

What this will mean though, is that changes to main might try to publish again, fail, and fail the build which I don't like. I'm going to write a script to deal with that.

**Comment by kierans** [comment]
@bfarrelly I've added a script that checks for the existence of the module in NPM and only publishes if it's not found.

**Review by bfarrelly — APPROVED** [review]

**Comment by kierans** [comment]
We can always add in a versioning policy later.

**Pull request merged**
